; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	C:\Users\Phee\Documents\Visual Studio 2015\Projects\Hello_World\Hello_World\Main3.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?Plus@@YAHH@Z					; Plus
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_n$ = -4						; size = 4
_main	PROC
; File c:\users\phee\documents\visual studio 2015\projects\hello_world\hello_world\main3.cpp
; Line 21
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 23
	mov	DWORD PTR _n$[ebp], 10			; 0000000aH
; Line 24
	mov	eax, DWORD PTR _n$[ebp]
	push	eax
	call	?Plus@@YAHH@Z				; Plus
	add	esp, 4
; Line 26
	xor	eax, eax
; Line 27
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?Plus@@YAHH@Z
_TEXT	SEGMENT
_sum$ = -8						; size = 4
_i$1 = -4						; size = 4
_n$ = 8							; size = 4
?Plus@@YAHH@Z PROC					; Plus, COMDAT
; File c:\users\phee\documents\visual studio 2015\projects\hello_world\hello_world\main3.cpp
; Line 11
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 13
	mov	DWORD PTR _sum$[ebp], 0
; Line 14
	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN4@Plus
$LN2@Plus:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN4@Plus:
	mov	ecx, DWORD PTR _i$1[ebp]
	cmp	ecx, DWORD PTR _n$[ebp]
	jg	SHORT $LN3@Plus
; Line 15
	mov	edx, DWORD PTR _sum$[ebp]
	add	edx, DWORD PTR _i$1[ebp]
	mov	DWORD PTR _sum$[ebp], edx
; Line 16
	jmp	SHORT $LN2@Plus
$LN3@Plus:
; Line 17
	mov	eax, DWORD PTR _sum$[ebp]
; Line 18
	mov	esp, ebp
	pop	ebp
	ret	0
?Plus@@YAHH@Z ENDP					; Plus
_TEXT	ENDS
END
